### PR TITLE
Disable 'upload artifact' workflow step - we have none

### PR DESCRIPTION
**Pull request by thockin**
Trying this

### CODE REVIEW

**Comment by pohly** [comment]
We have CodeQL enabled in https://github.com/go-logr/logr/settings/security_analysis (under "Code scanning"). According to https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning, "If you use the default CodeQL static analysis engine, then your results will display in your repository on GitHub automatically."

But I don't know whether any of this is working and/or results in SARIF files that we could upload here?

**Comment by thockin** [comment]
The block immediately below this also seem to upload results.sarif ?

**Comment by pohly** [comment]
Indeed. It has been like that since https://github.com/go-logr/logr/commit/dc28fa94e2b73c2ec7e9d269f1d67ebe76ca6092

@pnacht, can we remove the redundant (?) `actions/upload-artifact`?

**Comment by pohly** [comment]
One purpose of the `actions/upload-artifact` might have been to make the file available for manual download: we can get it via `Actions`. We don't need it, so if this was the intend, then we can remove the action.

Let's give @pnacht a bit more time, then I'll merge.

**Comment by pnacht** [comment]
Hey @thockin and @pohly. You can absolutely remove the upload-artifact if you wish.

It simply makes the SARIF file containing the results of the Scorecard scan available to the public as a workflow artifact (i.e. see [the latest run of the Scorecard Action](https://github.com/go-logr/logr/actions/runs/7254042461)). The results will still be available to maintainers in the [Security Dashboard](https://github.com/go-logr/logr/security/code-scanning) and to consumers through the [viewer](https://securityscorecards.dev/viewer/?uri=github.com/go-logr/logr).

**Comment by pohly** [comment]
@thockin: let's remove it entirely instead of just commenting it out.

**Comment by pnacht** [comment]
Ah, it's failing? Can you point me to a failing run so I can take a look?

I don't see one in https://github.com/go-logr/logr/actions/workflows/scorecard.yml:

Screenshot 2023-12-19 at 17 24 07

**Comment by thockin** [comment]
Yeah, weirdly it is not showing there, but it DID happen.

**Comment by thockin** [comment]
It failed on a dependabot PR.  Let's leave this open until we have a repro?

**Comment by pnacht** [comment]
> Yeah, weirdly it is not showing there, but it DID happen.

Maybe a maintainer re-ran the workflow? That can be done without a new commit. 

I don't think external contributors can see it, but you can go into the different runs in https://github.com/go-logr/logr/actions/workflows/scorecard.yml. If the failing run was retried, you should be able to see the results for previous attempts (see the [docs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#reviewing-previous-workflow-runs)).

**Pull request closed without merging**
